#include "RobotomyRequestForm.hpp"

RobotomyRequestForm::RobotomyRequestForm(const std::string &target)
    : AForm("Robotomy Request", 72, 45), target(target) {}




/*This function returns a pseudo-random integer between 0 and RAND_MAX (which is usually a big number like 32767).
% 2 gives the remainder when divided by 2, which will be either:
0 → even
1 → odd
So:
rand() % 2
Will randomly return 0 or 1 — with roughly 50% chance each.*/
	/* Random number
A truly random number comes from some unpredictable physical process (like radioactive decay or cosmic rays). Computers don’t naturally do that.

🌀 Pseudo-random number
This is what rand() gives you. It's:
Generated by a mathematical formula.
Looks random, but actually follows a predictable pattern.
If you use the same "starting point" (called a seed, like srand(42)), you’ll get the same sequence every time.
That’s why it's called pseudo (fake) random — it just appears random, but isn’t truly unpredictable.
In C++98, rand() is your tool for this. In modern C++, you'd use <random> for better randomness — but not needed here.*/
void RobotomyRequestForm::execute(Bureaucrat const &executor) const {
    if (!getIsSigned())
        throw FormNotSignedException();
    if (executor.getGrade() > getGradeRequiredToExecute())
        throw GradeTooLowException();

    std::cout << "Drilling noises... ";
    if (rand() % 2)
        std::cout << target << " has been robotomized successfully!\n";
    else
        std::cout << "Robotomy failed!\n";
}
